routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\JawabanController;
use App\Http\Controllers\KategoriController;

// Route untuk HomeController
Route::get('/', [HomeController::class, 'index']);

Route::get('/master', function () {
    return view('layout.master');
});
Route::get('/', function () {
    return view('welcome');
});


// Route untuk UserController
Route::resource('users', UserController::class);

// Route untuk ProfileController
Route::get('/profile', [ProfileController::class, 'index']);

Route::put('/profile/{id}', [ProfileController::class, 'update']);

// Route untuk PertanyaanController
Route::resource('pertanyaan', PertanyaanController::class);

// Route untuk JawabanController
Route::resource('jawaban', JawabanController::class);

// Route untuk KategoriController
Route::resource('kategori', KategoriController::class);

Auth::routes();


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Pertanyaan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    use HasFactory;

    protected $table = 'pertanyaan';

    protected $fillable = ['judul', 'isi', 'img', 'users_id', 'kategori_id'];

    public function jawabanpertanyaan()
    {
        return $this->hasManyThrough(User::class, Kategori::class);
    }
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use App\Models\jawabanPertanyaan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Pertanyaan;
use App\Models\Kategori;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\UploadedFile;



class PertanyaanController extends Controller
{
    /**
     * Menampilkan daftar pertanyaan.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $pertanyaan = Pertanyaan::all();
        return view('pertanyaan.index', ['pertanyaan' => $pertanyaan]);
    }

    public function create()
    {
        $kategori = Kategori::all();
        return view('pertanyaan.create', ['kategori' => $kategori]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
            'img' => 'required|mimes:jpg,jpeg,png|max:2048',
            // 'users_id' => 'required',
            'kategori_id' => 'required',
        ]);

        $imageName = time() . '.' . $request->img->extension();

        $request->img->move(public_path('img'), $imageName);

        DB::table('pertanyaan')->insert([
            'judul' => $request['judul'],
            'isi' => $request['isi'],
            'img' => $imageName,
            'users_id' => Auth::id(),
            'kategori_id' => $request['kategori_id'],
        ]);

        // $pertanyaan = new Pertanyaan();

        // $pertanyaan->judul = $request['judul'];
        // $pertanyaan->isi = $request['isi'];
        // $pertanyaan->users_id = $request['users_id'];
        // $pertanyaan->kategori_id = $request['kategori_id'];
        // $pertanyaan->img = $imageName;

        // $pertanyaan->save();
        return redirect('/pertanyaan');
    }

    public function show($id)
    {
        $pertanyaan = Pertanyaan::find($id);
        $jawaban = jawabanPertanyaan::where('pertanyaan_id', $id)->get();
        return view('pertanyaan.detail', [
            'pertanyaan' => $pertanyaan,
            'jawaban' => $jawaban,
        ]);
    }

    public function update($id, Request $request)
    {
        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
            'img' => 'required|mimes:jpg,jpeg,png|max:2048',
            'users_id' => 'required',
            'kategori_id' => 'required',
        ]);;

        $imageName = time() . '.' . $request->poster->extension();

        $request->poster->move(public_path('poster'), $imageName);

        DB::table('pertanyaan')
            ->where('id', $id)
            ->update([
                'judul' => $request['judul'],
                'isi' => $request['isi'],
                'img' => $imageName,
                'users_id' => $request['users_id'],
                'kategori_id' => $request['kategori_id'],
            ]);

        return redirect('/pertanyaan');
    }

    public function destroy($id)
    {
        DB::table('jawaban_pertanyaan')->where('pertanyaan_id', $id)->delete();
        DB::table('pertanyaan')->where('id', $id)->delete();

        return redirect('/pertanyaan');
    }

}

resources/views/pertanyaan/create.blade.php
@extends('layout.master')

@section('title', 'Tambahkan Pertanyaan')

@section('content')

<form action="/pertanyaan" method="POST" enctype="multipart/form-data">
    @csrf
<div class="form-group">
    <label >Judul Pertanyaan</label>
    <input type="text" class="form-control @error('judul') is-invalid @enderror" name="judul">
      @error('judul')
      <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </div>
  <div class="form-group">
    <label >Isi Pertanyaan</label>
    <input type="text" class="form-control @error('isi') is-invalid @enderror" name="isi">
      @error('isi')
      <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </div>
  
  <div class="form-group">
      <label>Kategori Pertanyaan</label>
      <select name="kategori_id" class="form-control @error('kategori_id') is-invalid @enderror" name="tahun">
          <option value="">--Pilih Kategori--</option>
          @forelse ($kategori as  $item)
                <option value="{{ $item->id }}">{{ $item->nama_kategori }}</option>
            @empty
                <option value="">Tidak Ada Kategori</option>
            @endforelse
      </select>
      @error('kategori_id')
      <div class="alert alert-danger">{{ $message }}</div>
      @enderror
  </div>
  <div class="form-group">
      <label >Image</label>
      <input type="file" class="form-control @error('img') is-invalid @enderror" name="img">
        <!-- @error('img') -->
        <!-- <div class="alert alert-danger">{{ $message }}</div> -->
        <!-- @enderror -->
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  </div>
</form>

@endsection

resources/views/pertanyaan/detail.blade.php
@extends('layout.master')

@section('title', 'Detail Pertanyaan')

@section('content')

    <div class="row">
        <div class="col">
            <div class="mb-5">
            <div class="">
                <h3 class="text-danger">{{$pertanyaan->judul}}</h3>
                <img src="{{asset('img/'.$pertanyaan->img) }}" style="height: 100px; width: 100px" class="card-img-top mb-3" alt="...">
            </div>
                <h4>Pertanyaan : {{$pertanyaan->isi}}</h4>
        </div>
        </div>
        <div class="col">
            <div class="card text-start">
                <div class="card-body">
                    <h4 class="card-title">
                        <div class="row">
                            <div class="col"><h4>Jawaban</h4></div>
                        </div>
                    </h4>
                    <div class="row">
                        <div class="col">
                            <div class="mb-3">
                                <form action="{{route('jawaban.store')}}" method="post">
                                    @csrf
                                    <input type="hidden" name="pertanyaan_id" value="{{$pertanyaan->id}}">
                                    <input type="text" class="form-control" name="isi_jawaban"/>
                                    <button class="btn btn-success mt-3" type="submit">Kirim Jawaban</button>
                                </form>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    

    @forelse ($jawaban as $keys => $item)
        <div class="card text-start">
            <div class="card-body">
                <div class="row">
                    <div class="col-11">
                        <div class="d-flex align-items-center">
                            <h5>{{$keys+1}} . {{$item->isi_jawaban}}</h5>
                        </div>
                    </div>
                    <div class="col">
                        @if ($item->users_id == Auth::user()->id)
                            <form action="{{route('jawaban.destroy', $item->id)}}" method="post">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger" type="submit">Hapus</button>
                            </form>
                        @endif
                        
                    </div>
                </div>
            </div>
        </div>
    @empty
        <div>Jawaban Kosong!</div>
    @endforelse

    
@endsection

resources/views/pertanyaan/index.blade.php
@extends('layout.master')

@section('title', 'Index Pertanyaan')

@section ('content')

<a href="/pertanyaan/create" class="btn btn-primary my-3">Tambah Pertanyaan</a>
<table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Pertanyaan</th>
        <th scope="col">Image</th>
        <th scope="col">Aksi</th>
      </tr>
    </thead>
    <tbody>
        @forelse ($pertanyaan as $keys=>$pertanyaans)
        <tr>
        <td scope="row">{{ $keys + 1 }}</td>
        <td>{{ $pertanyaans->isi }}</td>
        <td>
          <img src="{{asset('img/'.$pertanyaans->img) }}" style="height: 100px; width: 100px" class="card-img-top mb-3" alt="...">
        </td>
        <td class="d-flex">
          <a href="/pertanyaan/{{ $pertanyaans->id }}" class="btn btn-info btn-sm"><i class="bi bi-book"></i></a>

          @if ($pertanyaans->users_id == Auth::user()->id)
            <a href="" class="btn btn-warning btn-sm"><i class="bi bi-pencil-square"></i></a>
            <form action="/pertanyaan/{{ $pertanyaans->id }}" method="POST">
                @csrf
                @method('delete')
                <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash-fill"></i></button>
            </form>
          @endif

        </td>
        </tr>
    @empty
    <tr>
        <td>Pertanyaan Kosong!</td>
    </tr>
        
    @endforelse
        
    </tbody>
  </table>
@endsection